### ISSUE TITLE
Question about package.input

### ISSUE THREAD

**Issue by Adjective-Object** [LukeShay/yarn-berry-typescript-monorepo#1]
Hey, not sure if this is the right forum for this but I had a question about the input field in package.json

For full context: I've been doing the same thing on a project with yarn berry + jest + composite typescript projects. I remember having issues with qualified path resolution when trying to run tests with internal dependencies. If tests in package-a depended on package-b, they would try to resolve from the package.json's main field -- which pointed to the built outputs rather than the typescript inputs. That would cause the imports to fail, if the package-b hadn't been compiled yet.

Setting `"input": "src/..."` in package.json fixes this, but I don't remember what github issue pointed me towards that solution, and I can't find documentation on it _anywhere_. I was hoping you remembered, since your template repo is the only other code I could find that uses the seemingly nonstandard field.

**Comment by lukeshay** [comment]
This project is set up to use input for the rollup input. I don't actually use this anymore so I likely won't change anything. My preference would be to build and then run the tests because the package will be using the built files and not the typescript files.
